### ISSUE TITLE
DK Mountain implosion

### ISSUE THREAD

**Issue by loc** [loc/mario-kart#1]
I think the detector believes DK mountain is the setup screen because of the whiteness of the track. Give a little more room in the mode watcher.

**Comment by joekiller** [comment]
Others that crash it out at the beginning:
- Daisy Circuit
- Grumble
- Ghost Valley

**Comment by loc** [comment]
great--did you record them? i'm working on it now actually so it'd be great to have those videos.

**Comment by joekiller** [comment]
Interestingly enough, I had the reader running on my machine (using rtmp as well) and no crashes occurred.
